INSERT INTO DESIGNATION VALUES (1,'DIRECTOR',1);
INSERT INTO DESIGNATION VALUES (2,'MANAGER',2);
INSERT INTO DESIGNATION VALUES (3,'LEAD',3);
INSERT INTO DESIGNATION VALUES (4,'DEVELOPER',4);
INSERT INTO DESIGNATION VALUES (5,'DEVOPS',4);
INSERT INTO DESIGNATION VALUES (6,'QA',4);
INSERT INTO DESIGNATION VALUES (7,'INTERN',5);

INSERT INTO EMPLOYEE VALUES (1,'THOR',null,1);
INSERT INTO EMPLOYEE VALUES (2,'IRON MAN',1,2);
INSERT INTO EMPLOYEE VALUES (3,'HULK',1,3);
INSERT INTO EMPLOYEE VALUES (4,'CAPTAIN AMERICA',1,2);
INSERT INTO EMPLOYEE VALUES (5,'WAR MACHINE',2,6);
INSERT INTO EMPLOYEE VALUES (6,'VISION',2,5);
INSERT INTO EMPLOYEE VALUES (7,'FALCON',4,4);
INSERT INTO EMPLOYEE VALUES (8,'ANT MAN',4,3);
INSERT INTO EMPLOYEE VALUES (9,'SPIDER MAN',2,7);
INSERT INTO EMPLOYEE VALUES (10,'BLACK WIDOW',3,4)